# Generated by Django 6.0.3 on 2026-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0004_appointment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='uploads/default/default.png', upload_to='doctors'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(default='uploads/default/default.png', upload_to='patients'),
        ),
    ]
