# Generated by Django 6.0.3 on 2026-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0006_alter_doctor_photo_alter_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='uploads/default/default.png', upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(default='uploads/default/default.png', upload_to='patients'),
        ),
    ]
