# Generated by Django 6.0.3 on 2026-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0011_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(default='MBBS'),
        ),
    ]
