# Generated by Django 6.0.3 on 2026-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0012_doctor_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='prescription',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
