# Generated by Django 6.0.3 on 2026-06-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0014_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 3, 15, 20, 56, 258248, tzinfo=datetime.timezone.utc)),
        ),
    ]
