# Generated by Django 6.0.3 on 2026-06-07 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0015_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 7, 8, 15, 45, 679841, tzinfo=datetime.timezone.utc)),
        ),
    ]
