# Generated by Django 6.0.3 on 2026-06-07 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0016_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='completed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 7, 14, 29, 21, 377124, tzinfo=datetime.timezone.utc)),
        ),
    ]
